[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "/sub2api/**",
]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
requiredMountPath = "/app/data"
